# permissions for end users to view managedclustergroupworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedclustergroupwork-viewer-role
rules:
- apiGroups:
  - work.open-cluster-management-extension.io
  resources:
  - managedclustergroupworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - work.open-cluster-management-extension.io
  resources:
  - managedclustergroupworks/status
  verbs:
  - get
