# permissions for end users to view managedclustersupgrades.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedclustersupgrade-viewer-role
rules:
- apiGroups:
  - cluster.open-cluster-management-extension.io
  resources:
  - managedclustersupgrades
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.open-cluster-management-extension.io
  resources:
  - managedclustersupgrades/status
  verbs:
  - get
