
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - act.open-cluster-management-extension.io
  resources:
  - managedclustergroupacts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - act.open-cluster-management-extension.io
  resources:
  - managedclustergroupacts/finalizers
  verbs:
  - update
- apiGroups:
  - act.open-cluster-management-extension.io
  resources:
  - managedclustergroupacts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - action.open-cluster-management.io
  resources:
  - managedclusteraction
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.open-cluster-management-extension.io
  resources:
  - managedclustersupgrades
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.open-cluster-management-extension.io
  resources:
  - managedclustersupgrades/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.open-cluster-management-extension.io
  resources:
  - managedclustersupgrades/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - view.open-cluster-management.io
  resources:
  - managedclusterview
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - work.open-cluster-management-extension.io
  resources:
  - managedclustergroupworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - work.open-cluster-management-extension.io
  resources:
  - managedclustergroupworks/finalizers
  verbs:
  - update
- apiGroups:
  - work.open-cluster-management-extension.io
  resources:
  - managedclustergroupworks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - work.open-cluster-management.io
  resources:
  - manifestwork
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
