apiVersion: cluster.open-cluster-management-extension.io/v1beta1
kind: ManagedClustersUpgrade
metadata:
  name: managedclustersupgrade-sample
spec:
  clusters:
  - name: myCluster
  ocpOperators:
    approveAllUpgrades: true
